### ISSUE TITLE
After stage 2: write guide

### ISSUE THREAD

**Issue by espen42** [enonic/nextjs-enonic-starter#29]
- [ ] Intro
- [x] Get started
- [x] Task: add a query with variables: folder
- [x] Task: add component for page rendering
- [ ] Preview in CS https://github.com/enonic/starter-nextjs/issues/37
- [x] Props processing

- [ ] Simplify guide: 
    - [ ] Move the entire _Understanding the code_ section out from chapter 3 (replace with a link or an ultra-compact overview) and into a separate chapter. Appendix? Same as API chapter?
    - [ ] Same with the _Workflow_ section in chapter 4.
